### ISSUE TITLE
prestashop-module-abandoned-cart

### ISSUE THREAD

**Issue by realmofevil** [josAlba/prestashop-module-producto-view#1]
Hello, couldn't find any other way to contact you.
What happened to your prestashop-module-abandoned-cart? I wanted to try it but you seem to have deleted/hidden the repository.

**Comment by josAlba** [comment]
Hi,
Delete the repository due to lack of time to update.
But if you are interested in using it, I hung it up again greetings.

https://github.com/josAlba/prestashop-module-abandoned-cart

**Comment by realmofevil** [comment]
Hi again,
and many thanks!
